sudo: false
language: node_js
node_js:
  - '12'
  - '10'
after_success: npm run coverage

env:
  global:
    - SAUCE_USERNAME='shtylman-superagent'
    - SAUCE_ACCESS_KEY='39a45464-cb1d-4b8d-aa1f-83c7c04fa673'

matrix:
  include:
    - node_js: "10"
      env: BROWSER=1
  include:
    - node_js: "12"
      env: HTTP2_TEST=1
